framework:
    messenger:
        transports:
            producer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\Infrastructure\Messenger\OutboundMessageSerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'to-device'
#                    kafka_conf:
#                        security.protocol: 'sasl_ssl'
#                        ssl.ca.location: '%kernel.project_dir%/config/kafka/ca.pem'
#                        sasl.username: '%env(KAFKA_SASL_USERNAME)%'
#                        sasl.password: '%env(KAFKA_SASL_PASSWORD)%'
#                        sasl.mechanisms: 'SCRAM-SHA-256'
            consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\Infrastructure\Messenger\InboundMessageSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: "from-device"
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'test' # should be unique per consumer
#                        security.protocol: 'sasl_ssl'
#                        ssl.ca.location: '%kernel.project_dir%/config/kafka/ca.pem'
#                        sasl.username: '%env(KAFKA_SASL_USERNAME)%'
#                        sasl.password: '%env(KAFKA_SASL_PASSWORD)%'
#                        sasl.mechanisms: 'SCRAM-SHA-256'
#                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Application\OutboundMessage: producer
            App\Application\InboundMessage: consumer